insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_1', 'Prenom_DJ_1', 'Pseudo_DJ_1', '1998-9-4', 'Add_DJ_1', 'Asie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_2', 'Prenom_DJ_2', 'Pseudo_DJ_2', '1997-1-22', 'Add_DJ_2', 'Amérique du Nord', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_3', 'Prenom_DJ_3', 'Pseudo_DJ_3', '1982-4-9', 'Add_DJ_3', 'Amérique Centrale', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_4', 'Prenom_DJ_4', 'Pseudo_DJ_4', '2003-1-13', 'Add_DJ_4', 'Europe', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_5', 'Prenom_DJ_5', 'Pseudo_DJ_5', '2004-12-2', 'Add_DJ_5', 'Afrique', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_6', 'Prenom_DJ_6', 'Pseudo_DJ_6', '1999-12-14', 'Add_DJ_6', 'Amérique Centrale', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_7', 'Prenom_DJ_7', 'Pseudo_DJ_7', '1980-11-25', 'Add_DJ_7', 'Amérique du Nord', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_8', 'Prenom_DJ_8', 'Pseudo_DJ_8', '1988-6-18', 'Add_DJ_8', 'Europe', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_9', 'Prenom_DJ_9', 'Pseudo_DJ_9', '1996-1-23', 'Add_DJ_9', 'Amérique du Sud', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_10', 'Prenom_DJ_10', 'Pseudo_DJ_10', '2005-6-19', 'Add_DJ_10', 'Océanie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_11', 'Prenom_DJ_11', 'Pseudo_DJ_11', '2005-3-27', 'Add_DJ_11', 'Asie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_12', 'Prenom_DJ_12', 'Pseudo_DJ_12', '1980-6-18', 'Add_DJ_12', 'Asie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_13', 'Prenom_DJ_13', 'Pseudo_DJ_13', '1997-6-16', 'Add_DJ_13', 'Afrique', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_14', 'Prenom_DJ_14', 'Pseudo_DJ_14', '1997-7-25', 'Add_DJ_14', 'Afrique', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_15', 'Prenom_DJ_15', 'Pseudo_DJ_15', '1986-1-19', 'Add_DJ_15', 'Amérique du Nord', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_16', 'Prenom_DJ_16', 'Pseudo_DJ_16', '1994-4-20', 'Add_DJ_16', 'Amérique du Sud', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_17', 'Prenom_DJ_17', 'Pseudo_DJ_17', '1988-11-13', 'Add_DJ_17', 'Amérique du Nord', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_18', 'Prenom_DJ_18', 'Pseudo_DJ_18', '2003-10-15', 'Add_DJ_18', 'Amérique du Sud', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_19', 'Prenom_DJ_19', 'Pseudo_DJ_19', '1999-11-15', 'Add_DJ_19', 'Afrique', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_20', 'Prenom_DJ_20', 'Pseudo_DJ_20', '2001-11-19', 'Add_DJ_20', 'Europe', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_21', 'Prenom_DJ_21', 'Pseudo_DJ_21', '2001-12-11', 'Add_DJ_21', 'Asie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_22', 'Prenom_DJ_22', 'Pseudo_DJ_22', '1994-3-24', 'Add_DJ_22', 'Amérique du Nord', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_23', 'Prenom_DJ_23', 'Pseudo_DJ_23', '1997-11-11', 'Add_DJ_23', 'Amérique du Sud', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_24', 'Prenom_DJ_24', 'Pseudo_DJ_24', '1983-8-16', 'Add_DJ_24', 'Océanie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_25', 'Prenom_DJ_25', 'Pseudo_DJ_25', '1990-9-13', 'Add_DJ_25', 'Asie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_26', 'Prenom_DJ_26', 'Pseudo_DJ_26', '2001-8-11', 'Add_DJ_26', 'Asie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_27', 'Prenom_DJ_27', 'Pseudo_DJ_27', '1981-2-5', 'Add_DJ_27', 'Europe', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_28', 'Prenom_DJ_28', 'Pseudo_DJ_28', '1985-9-20', 'Add_DJ_28', 'Asie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_29', 'Prenom_DJ_29', 'Pseudo_DJ_29', '1983-6-11', 'Add_DJ_29', 'Asie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_30', 'Prenom_DJ_30', 'Pseudo_DJ_30', '1981-1-12', 'Add_DJ_30', 'Amérique du Sud', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_31', 'Prenom_DJ_31', 'Pseudo_DJ_31', '1989-7-1', 'Add_DJ_31', 'Amérique Centrale', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_32', 'Prenom_DJ_32', 'Pseudo_DJ_32', '1992-4-9', 'Add_DJ_32', 'Europe', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_33', 'Prenom_DJ_33', 'Pseudo_DJ_33', '2004-8-7', 'Add_DJ_33', 'Asie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_34', 'Prenom_DJ_34', 'Pseudo_DJ_34', '1991-3-28', 'Add_DJ_34', 'Océanie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_35', 'Prenom_DJ_35', 'Pseudo_DJ_35', '1980-8-25', 'Add_DJ_35', 'Océanie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_36', 'Prenom_DJ_36', 'Pseudo_DJ_36', '1988-5-2', 'Add_DJ_36', 'Océanie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_37', 'Prenom_DJ_37', 'Pseudo_DJ_37', '1984-10-18', 'Add_DJ_37', 'Amérique du Nord', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_38', 'Prenom_DJ_38', 'Pseudo_DJ_38', '1990-1-1', 'Add_DJ_38', 'Amérique du Sud', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_39', 'Prenom_DJ_39', 'Pseudo_DJ_39', '1981-1-22', 'Add_DJ_39', 'Amérique du Sud', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_40', 'Prenom_DJ_40', 'Pseudo_DJ_40', '1983-7-1', 'Add_DJ_40', 'Asie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_41', 'Prenom_DJ_41', 'Pseudo_DJ_41', '1996-5-24', 'Add_DJ_41', 'Amérique du Nord', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_42', 'Prenom_DJ_42', 'Pseudo_DJ_42', '1992-7-3', 'Add_DJ_42', 'Asie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_43', 'Prenom_DJ_43', 'Pseudo_DJ_43', '1983-4-10', 'Add_DJ_43', 'Afrique', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_44', 'Prenom_DJ_44', 'Pseudo_DJ_44', '1992-6-10', 'Add_DJ_44', 'Asie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_45', 'Prenom_DJ_45', 'Pseudo_DJ_45', '1982-8-8', 'Add_DJ_45', 'Asie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_46', 'Prenom_DJ_46', 'Pseudo_DJ_46', '1992-5-22', 'Add_DJ_46', 'Amérique Centrale', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_47', 'Prenom_DJ_47', 'Pseudo_DJ_47', '1980-9-15', 'Add_DJ_47', 'Océanie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_48', 'Prenom_DJ_48', 'Pseudo_DJ_48', '1999-1-10', 'Add_DJ_48', 'Amérique du Nord', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_49', 'Prenom_DJ_49', 'Pseudo_DJ_49', '1992-11-3', 'Add_DJ_49', 'Amérique Centrale', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_50', 'Prenom_DJ_50', 'Pseudo_DJ_50', '1980-12-12', 'Add_DJ_50', 'Amérique Centrale', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_51', 'Prenom_DJ_51', 'Pseudo_DJ_51', '2005-2-27', 'Add_DJ_51', 'Afrique', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_52', 'Prenom_DJ_52', 'Pseudo_DJ_52', '1988-7-8', 'Add_DJ_52', 'Océanie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_53', 'Prenom_DJ_53', 'Pseudo_DJ_53', '1999-10-2', 'Add_DJ_53', 'Océanie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_54', 'Prenom_DJ_54', 'Pseudo_DJ_54', '1997-12-8', 'Add_DJ_54', 'Amérique Centrale', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_55', 'Prenom_DJ_55', 'Pseudo_DJ_55', '1985-10-28', 'Add_DJ_55', 'Amérique du Nord', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_56', 'Prenom_DJ_56', 'Pseudo_DJ_56', '1996-3-19', 'Add_DJ_56', 'Amérique Centrale', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_57', 'Prenom_DJ_57', 'Pseudo_DJ_57', '1983-5-20', 'Add_DJ_57', 'Europe', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_58', 'Prenom_DJ_58', 'Pseudo_DJ_58', '2001-5-5', 'Add_DJ_58', 'Afrique', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_59', 'Prenom_DJ_59', 'Pseudo_DJ_59', '2002-11-12', 'Add_DJ_59', 'Océanie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_60', 'Prenom_DJ_60', 'Pseudo_DJ_60', '1988-10-8', 'Add_DJ_60', 'Afrique', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_61', 'Prenom_DJ_61', 'Pseudo_DJ_61', '1981-11-2', 'Add_DJ_61', 'Asie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_62', 'Prenom_DJ_62', 'Pseudo_DJ_62', '1982-1-17', 'Add_DJ_62', 'Amérique du Sud', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_63', 'Prenom_DJ_63', 'Pseudo_DJ_63', '2003-3-15', 'Add_DJ_63', 'Amérique du Nord', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_64', 'Prenom_DJ_64', 'Pseudo_DJ_64', '1991-4-11', 'Add_DJ_64', 'Asie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_65', 'Prenom_DJ_65', 'Pseudo_DJ_65', '1982-7-11', 'Add_DJ_65', 'Océanie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_66', 'Prenom_DJ_66', 'Pseudo_DJ_66', '2005-5-9', 'Add_DJ_66', 'Asie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_67', 'Prenom_DJ_67', 'Pseudo_DJ_67', '1999-11-26', 'Add_DJ_67', 'Amérique du Nord', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_68', 'Prenom_DJ_68', 'Pseudo_DJ_68', '1988-7-2', 'Add_DJ_68', 'Amérique du Sud', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_69', 'Prenom_DJ_69', 'Pseudo_DJ_69', '1996-7-24', 'Add_DJ_69', 'Amérique Centrale', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_70', 'Prenom_DJ_70', 'Pseudo_DJ_70', '1981-3-25', 'Add_DJ_70', 'Amérique Centrale', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_71', 'Prenom_DJ_71', 'Pseudo_DJ_71', '1990-12-23', 'Add_DJ_71', 'Amérique du Sud', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_72', 'Prenom_DJ_72', 'Pseudo_DJ_72', '1984-5-25', 'Add_DJ_72', 'Afrique', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_73', 'Prenom_DJ_73', 'Pseudo_DJ_73', '1985-9-4', 'Add_DJ_73', 'Amérique du Sud', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_74', 'Prenom_DJ_74', 'Pseudo_DJ_74', '1999-3-13', 'Add_DJ_74', 'Océanie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_75', 'Prenom_DJ_75', 'Pseudo_DJ_75', '1984-5-15', 'Add_DJ_75', 'Amérique du Sud', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_76', 'Prenom_DJ_76', 'Pseudo_DJ_76', '1990-4-23', 'Add_DJ_76', 'Océanie', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_77', 'Prenom_DJ_77', 'Pseudo_DJ_77', '1981-1-6', 'Add_DJ_77', 'Europe', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_78', 'Prenom_DJ_78', 'Pseudo_DJ_78', '2003-5-11', 'Add_DJ_78', 'Europe', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_79', 'Prenom_DJ_79', 'Pseudo_DJ_79', '1989-8-18', 'Add_DJ_79', 'Afrique', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_80', 'Prenom_DJ_80', 'Pseudo_DJ_80', '1989-2-16', 'Add_DJ_80', 'Asie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_81', 'Prenom_DJ_81', 'Pseudo_DJ_81', '1996-12-15', 'Add_DJ_81', 'Océanie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_82', 'Prenom_DJ_82', 'Pseudo_DJ_82', '2004-11-19', 'Add_DJ_82', 'Amérique du Nord', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_83', 'Prenom_DJ_83', 'Pseudo_DJ_83', '1990-10-20', 'Add_DJ_83', 'Océanie', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_84', 'Prenom_DJ_84', 'Pseudo_DJ_84', '1983-11-10', 'Add_DJ_84', 'Amérique du Nord', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_85', 'Prenom_DJ_85', 'Pseudo_DJ_85', '1991-9-6', 'Add_DJ_85', 'Amérique du Nord', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_86', 'Prenom_DJ_86', 'Pseudo_DJ_86', '1986-3-25', 'Add_DJ_86', 'Afrique', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_87', 'Prenom_DJ_87', 'Pseudo_DJ_87', '1999-2-6', 'Add_DJ_87', 'Amérique du Nord', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_88', 'Prenom_DJ_88', 'Pseudo_DJ_88', '1995-4-27', 'Add_DJ_88', 'Amérique du Sud', 'Hard Style', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_89', 'Prenom_DJ_89', 'Pseudo_DJ_89', '1999-9-8', 'Add_DJ_89', 'Océanie', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_90', 'Prenom_DJ_90', 'Pseudo_DJ_90', '2000-9-23', 'Add_DJ_90', 'Océanie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_91', 'Prenom_DJ_91', 'Pseudo_DJ_91', '2001-2-25', 'Add_DJ_91', 'Europe', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_92', 'Prenom_DJ_92', 'Pseudo_DJ_92', '1986-3-18', 'Add_DJ_92', 'Amérique Centrale', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_93', 'Prenom_DJ_93', 'Pseudo_DJ_93', '1999-1-9', 'Add_DJ_93', 'Afrique', 'House', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_94', 'Prenom_DJ_94', 'Pseudo_DJ_94', '1994-11-8', 'Add_DJ_94', 'Amérique du Sud', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_95', 'Prenom_DJ_95', 'Pseudo_DJ_95', '2003-2-15', 'Add_DJ_95', 'Océanie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_96', 'Prenom_DJ_96', 'Pseudo_DJ_96', '2005-8-13', 'Add_DJ_96', 'Asie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_97', 'Prenom_DJ_97', 'Pseudo_DJ_97', '1998-6-3', 'Add_DJ_97', 'Asie', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_98', 'Prenom_DJ_98', 'Pseudo_DJ_98', '2000-10-23', 'Add_DJ_98', 'Amérique du Sud', 'Electro', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_99', 'Prenom_DJ_99', 'Pseudo_DJ_99', '1993-10-24', 'Add_DJ_99', 'Afrique', 'EDM', '1');
insert into DJ (Nom, Prenom, Pseudo, Date_de_Naissance, Adresse, Continent, Style, Actif) values ('Nom_DJ_100', 'Prenom_DJ_100', 'Pseudo_DJ_100', '2002-6-7', 'Add_DJ_100', 'Amérique du Sud', 'Electro', '1');
