insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Berghain', 'Berlin', 'Allemagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Fabric', 'Londres', 'Royaume-Uni', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Output', 'Brooklyn', 'États-Unis', 'Amérique du Nord');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Space', 'Ibiza', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Amnesia', 'Ibiza', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Pacha', 'Ibiza', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Ushuaïa', 'Ibiza', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Hï Ibiza', 'Ibiza', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Cavo Paradiso', 'Mykonos', 'Grèce', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('DC10', 'Ibiza', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Watergate', 'Berlin', 'Allemagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Ministry of Sound', 'Londres', 'Royaume-Uni', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Echostage', 'Washington D.C.', 'États-Unis', 'Amérique du Nord');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Output', 'New York', 'États-Unis', 'Amérique du Nord');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Amsterdam Dance Event (ADE)', 'Amsterdam', 'Pays-Bas', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Womb', 'Tokyo', 'Japon', 'Asie');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Zouk', 'Singapour', 'Singapour', 'Asie');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Omnia', 'Las Vegas', 'États-Unis', 'Amérique du Nord');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Pacha', 'Barcelone', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Elrow', 'Barcelone', 'Espagne', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Rex Club', 'Paris', 'France', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Concrete', 'Paris', 'France', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Faust', 'Paris', 'France', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Warung Beach Club', 'Itajaí', 'Brésil', 'Amérique du Sud');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('D-Edge', 'São Paulo', 'Brésil', 'Amérique du Sud');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Mandarino Club', 'Rio de Janeiro', 'Brésil', 'Amérique du Sud');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Crobar Buenos Aires', 'Buenos Aires', 'Argentine', 'Amérique du Sud');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Cocoricó', 'Riccione', 'Italie', 'Europe');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Home Nightclub', 'Sydney', 'Australie', 'Océanie');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Marquee Sydney', 'Sydney', 'Australie', 'Océanie');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Revolver Upstairs', 'Melbourne', 'Australie', 'Océanie');
insert into Lieu (Nom_Lieu, Ville, Pays, Continent) values ('Elsewhere', 'Gold Coast', 'Australie', 'Océanie');
